name: github actions plsh
on:
  push:
    branches:
    -  main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:     
      - name: Install dependencies
        run: |
          aws --version
          
          
