name: github actions plsh
on:
  push:
    branches:
    -  main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:     
      - name: Install dependencies
        run: |
          ls -lh
          aws --version
          aws s3 ls
          pwd
#          /usr/bin/bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SEC_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_SESSION_TOKEN: ${{ secrets.SESS_TOKEN }}
          
