name: github actions plsh
on:
  push:
    branches:
    -  main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      RELEASE_NAME: kushal
    defaults: 
      run:
        working-directory: build/docker
    steps:     
      - name : check version
        shell: bash
        run: |
          aws --version
          
          
