name: github actions plsh
on:
  push:
    branches:
    -  main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      RELEASE_NAME: kushal
    defaults: 
      run:
        working-directory: build/docker
    steps:
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
          rootdir: ""    # defaults to "PWD"
          workdir: ""    # defaults to "PWD/unfor19-awscli"
          
      - run: |
          aws --version
          
